const P=(n,cls,content)=>`<article class="sheet ${n%2===0?'left':'right'} ${cls}" data-page="${n}" aria-label="Page ${n}">${content}</article>`;
const I=(name,cls,alt)=>`<img class="${cls}" src="selected/${name}" alt="${alt}">`;
const pages=[
P(1,'p01',`<div class="seven">SEVEN</div><div class="ru">СЕМЬ ЗИМ</div><div class="dates">2019—2026</div><div class="rule slash"></div><div class="winters">WINTERS</div>`),
P(2,'p02',`<span class="reg"></span><p class="meta moscow">MOSCOW<br>55.7558 N<br>37.6173 E</p>`),
P(3,'p03 black',`<div class="year">2019</div><div class="arrival-word">ПРИБЫТИЕ / ARRIVAL</div>`),
P(4,'p04',`${I('01-arrival.png','airport-small','Arrival outside a Moscow airport')}<div class="index">01</div><p class="meta">MOSCOW<br>2019.09.04<br>FRAME 001</p>`),
P(5,'p05',`${I('01-arrival.png','arrival-detail','Cropped airport arrival')}<p class="meta date-stamp">ARRIVAL / 19:08</p><div class="edgeword">МОСКВА</div>`),
P(6,'p06',`${I('02-rain-window.png','bleed rain','Rain-covered car window')}<p class="meta coords">55.7558 N<br>37.6173 E</p><p class="coldline">FIRST RUSSIA / THROUGH GLASS</p>`),
P(7,'p07',`${I('03-dorm-room.png','room','First dormitory room')}<p class="meta roomtag">ROOM / 04</p><div class="roomno">04</div>`),
P(8,'p08',`${I('05-snow-night.png','snow-slice','Snowy residential street at night')}<p class="meta temp">2020 / −17°C</p>`),
P(9,'p09',`${I('05-snow-night.png','snow-slice','Continuation of snowy street')}<div class="winter">ЗИМА</div><span class="page-no">09</span>`),
P(10,'p10',`${I('04-first-meal.png','food-a','Food by the dormitory window')}${I('04-first-meal.png','food-b','Cropped food and window detail')}<div class="receipt meta"><span>МОСКВА</span><br><strong>22:48</strong><br>−12°C<br>DINNER / 01</div><span class="page-no red">10</span>`),
P(11,'p11 black',`${I('11-supermarket.png','market-wide','Supermarket aisle')}${I('11-supermarket.png','market-detail','Supermarket fragment')}<p class="meta market-copy">DAILY STOCK<br>UNIT 014<br>2021—02</p><div class="big22">22</div><span class="page-no">11</span>`),
P(12,'p12',`${I('08-spring-grass.png','grass','Friends sitting in spring grass')}${I('10-birthday.png','birthday-frag','Birthday flash photograph fragment')}<div class="together">TO<br>GE<br>THER</div><p class="meta">2021<br>WARM<br>FRAME</p><span class="page-no red">12</span>`),
P(13,'p13',`${I('10-birthday.png','birthday','Birthday flash photograph with friends')}${I('08-spring-grass.png','grass-frag','Spring grass fragment')}<p class="meta flash">FLASH / 1⁄60<br>ROOM UNKNOWN</p><span class="page-no">13</span>`),
P(14,'p14',`<div class="years">2022<br><b>2023</b><br>2024</div><span class="page-no red">14</span>`),
P(15,'p15',`<div class="strip">${I('03-dorm-room.png','','Dorm room fragment')}${I('04-first-meal.png','','Food fragment')}${I('11-supermarket.png','','Supermarket fragment')}</div><p class="meta frame-index">003 / 004 / 011<br>NO DESCRIPTION</p><span class="page-no">15</span>`),
P(16,'p16 black',`${I('09-late-metro.png','metro','Late-night metro carriage')}<div class="trackno">23</div><p class="meta">METRO<br>23:47<br>LINE / 07</p><span class="page-no">16</span>`),
P(17,'p17',`${I('14-sleeper-train.png','train','Sleeper train compartment')}${I('12-bus-window.png','bus','Residential blocks through a bus window')}<div class="route">02</div><p class="meta">MOVEMENT<br>02:20—04:37</p><span class="page-no red">17</span>`),
P(18,'p18 black',`${I('15-thesis-desk.png','desk','Thesis desk at night')}<p class="meta clock">03:41 / THESIS</p><span class="page-no">18</span>`),
P(19,'p19 black',`${I('15-thesis-desk.png','desk-detail','Dark thesis desk detail')}<div class="rule crop-line"></div><p class="meta thesis">NIGHT WORK<br>REV. 07<br>UNSAVED</p><span class="page-no">19</span>`),
P(20,'p20',`${I('17-tram-melt.png','tram','Tram in melting snow')}<p class="meta ordinary">ORDINARY RUSSIA<br>ROUTE 17<br>−02°C</p><div class="year26">26</div><span class="page-no">20</span>`),
P(21,'p21',`${I('18-entrance-hall.png','hall','Apartment entrance hall')}<p class="meta apt">ENTRANCE 4<br>APT. 137<br>HOME / QUESTION</p><div class="number">137</div><span class="page-no red">21</span>`),
P(22,'p22',`<div class="rule tiny-red"></div><p class="later">СЕМЬ ЗИМ СПУСТЯ</p><span class="page-no red">22</span>`),
P(23,'p23',`${I('19-early-morning-window.png','morning','Early morning apartment window')}<p class="meta morning-meta">04:30<br>IT WAS ALREADY LIGHT</p><div class="window-word">ОКНО</div><span class="page-no">23</span>`),
P(24,'p24',`${I('20-final-car-window.png','final-slice','Moscow through a moving car window')}<p class="meta final-year">MOSCOW / 2026</p>`),
P(25,'p25',`${I('20-final-car-window.png','final-slice','Continuation of the final moving-car view')}<span class="page-no">25</span>`),
P(26,'p26',`<div class="rule backline"></div><p class="meta backmeta">MOSCOW<br>2019—2026</p><p class="meta archive-code">SW / ARCHIVE / 026</p>`)
];
function renderReader(){const root=document.querySelector('#reader');for(let i=0;i<pages.length;i+=2){const s=document.createElement('section');s.className='spread';s.innerHTML=pages[i]+(pages[i+1]||'<article class="sheet empty-sheet"></article>');root.appendChild(s)}const spreads=[...root.querySelectorAll('.spread')];let current=0,busy=false,startX=0,swiped=false;const label=document.querySelector('#spread-label'),prev=document.querySelector('#prev'),next=document.querySelector('#next');function sync(){spreads.forEach((s,i)=>{s.classList.toggle('active',i===current);s.classList.remove('under')});label.textContent=`${String(current+1).padStart(2,'0')} / ${String(spreads.length).padStart(2,'0')}`;prev.disabled=current===0;next.disabled=current===spreads.length-1}function turn(dir){const target=current+dir;if(busy||target<0||target>=spreads.length)return;busy=true;const source=spreads[current].children[dir>0?1:0];const leaf=source.cloneNode(true);leaf.classList.add('flip-leaf',dir>0?'next':'prev');spreads[target].classList.add('under');root.appendChild(leaf);setTimeout(()=>{spreads[current].classList.remove('active');current=target;spreads[current].classList.add('active')},370);leaf.addEventListener('animationend',()=>{leaf.remove();busy=false;sync()},{once:true})}root.addEventListener('click',e=>{if(busy||swiped){swiped=false;return}const r=root.getBoundingClientRect();turn(e.clientX<r.left+r.width/2?-1:1)});root.addEventListener('pointerdown',e=>{startX=e.clientX;swiped=false});root.addEventListener('pointerup',e=>{const dx=e.clientX-startX;if(Math.abs(dx)>70){swiped=true;turn(dx<0?1:-1)}});prev.onclick=e=>{e.stopPropagation();turn(-1)};next.onclick=e=>{e.stopPropagation();turn(1)};addEventListener('keydown',e=>{if(e.key==='ArrowLeft')turn(-1);if(e.key==='ArrowRight'||e.key===' '){e.preventDefault();turn(1)}});sync()}
function renderOverview(){const root=document.querySelector('#overview');for(let i=0;i<pages.length;i+=2){const s=document.createElement('section');s.className='overview-spread';s.innerHTML=pages[i]+(pages[i+1]||'');const n=document.createElement('span');n.className='page-no-ui';n.textContent=`${String(i+1).padStart(2,'0')}—${String(Math.min(i+2,pages.length)).padStart(2,'0')}`;s.appendChild(n);root.appendChild(s)}}
